#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "watchyourlan"
name = "WatchYourLAN"
description.en = "Lightweight network IP scanner with web GUI"
description.fr = "Scanner IP réseau léger avec interface graphique Web"

version = "2.1.3~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
admindoc = "https://github.com/aceberg/WatchYourLAN/blob/main/docs/VLAN_ARP_SCAN.md"
code = "https://github.com/aceberg/WatchYourLAN"
fund = "https://boosty.to/aceberg/donate"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = ["amd64", "armhf", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/aceberg/WatchYourLAN/releases/download/2.1.3/watchyourlan_2.1.3_linux_amd64.tar.gz"
    amd64.sha256 = "0516b8a65d39232e7bad7d58e5c73bd91fc51d72568447a5eac8659350e9f453"
    arm64.url = "https://github.com/aceberg/WatchYourLAN/releases/download/2.1.3/watchyourlan_2.1.3_linux_arm64.tar.gz"
    arm64.sha256 = "74beacd0ffad4f5964d9c9a44a558fc31f78a64a594553ba1c233b0338d03f07"
    armhf.url = "https://github.com/aceberg/WatchYourLAN/releases/download/2.1.3/watchyourlan_2.1.3_linux_armv7.tar.gz"
    armhf.sha256 = "23e6352c95e09fb08ef6b8e1d71ca2b12922c63f7f098b78e0b3de3c7163c448"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "watchyourlan_.*_linux_amd64.tar.gz"
    autoupdate.asset.armhf = "watchyourlan_.*_linux_armv7.tar.gz"
    autoupdate.asset.arm64 = "watchyourlan_.*_linux_arm64.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "sqlite3, arp-scan"
