#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "watchyourlan"
name = "WatchYourLAN"
description.en = "Lightweight network IP scanner with web GUI"
description.fr = "Scanner IP réseau léger avec interface graphique Web"

version = "2.1.4~ynh2"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
admindoc = "https://github.com/aceberg/WatchYourLAN/blob/main/docs/VLAN_ARP_SCAN.md"
code = "https://github.com/aceberg/WatchYourLAN"
fund = "https://boosty.to/aceberg/donate"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "armhf", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/aceberg/WatchYourLAN/releases/download/2.1.4/watchyourlan_2.1.4_linux_amd64.tar.gz"
    amd64.sha256 = "20f746f800f737ab05419fea7bd8b0dccbb0ba54696890aa9b415f42de68f459"
    arm64.url = "https://github.com/aceberg/WatchYourLAN/releases/download/2.1.4/watchyourlan_2.1.4_linux_arm64.tar.gz"
    arm64.sha256 = "5bd7609d3f4c4401e68c20051369a007c103abeed921e57b93563048ac0d6ad4"
    armhf.url = "https://github.com/aceberg/WatchYourLAN/releases/download/2.1.4/watchyourlan_2.1.4_linux_armv7.tar.gz"
    armhf.sha256 = "351b92c6d8efb12219da7f83f04421a15e8d0f11b3ed39927d6707414bd6c214"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "watchyourlan_.*_linux_amd64.tar.gz"
    autoupdate.asset.armhf = "watchyourlan_.*_linux_armv7.tar.gz"
    autoupdate.asset.arm64 = "watchyourlan_.*_linux_arm64.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "sqlite3, arp-scan"
