arp_args: ""
color: dark
hist_in_db: false
host: 127.0.0.1
ifaces: __NETWORK_INTERFACES__
influx_addr: ""
influx_bucket: ""
influx_enable: false
influx_org: ""
influx_skip_tls: false
influx_token: ""
log_level: info
nodepath: ""
pg_connect: "postgres://__DB_USER__:__DB_PWD__@localhost:5432/__DB_NAME__?sslmode=disable"
port: "__PORT__"
shoutrrr_url: ""
theme: sand
timeout: 60
trim_hist: 48
use_db: postgres
